config:
  spring_datasource_username: root
  # V1__inital_schema: |
  #   USE pages;
  #   create table pages(
  #   id bigint(20) not null auto_increment,
  #   business_name VARCHAR(50),
  #   address VARCHAR(50),
  #   category_id bigint(20),
  #   contact_number VARCHAR(50),
  #   primary key (id)
  #   )
  #   engine = innodb
  #   default charset = utf8;


deployment:
  containerPort: 3306

secrets:
  SDP: cGFzc3dvcmQ=


service:
  port: 3306
  type: ClusterIP
  protocol: TCP
  targetPort: 3306

image:
  repository: mysql
  tag: "8.0"


env:
  MYSQL_SERVICE_HOST: mysql
  MYSQL_SERVICE_PORT: 3306
  MYSQL_DATABASE: pages


volumeMounts:
  mountPath: /var/lib/mysql

job:
  image:
    repository: flyway/flyway
    tag: "6.4.4"
  env:
    FLYWAY_URL: jdbc:mysql://pages-mysql/pages
    FLYWAY_USER: root
    FLYWAY_PLACEHOLDER_REPLACEMENT: true

pv:
  capacity:
    storage: 3Gi
  accessMode: ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/dev"
pvc:
  resources:
    requests:
      storage: 1Gi

storageClass:
  provisioner: k8s.io/minikube-hostpath
  reclaimPolicy: Delete
  volumeBindingMode: Immediate